project:
  type: website
  output-dir: docs
website:
  title: "Ayush Raj Dahal"
  favicon: favicon.ico
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      # - projects.qmd
      - icon: github
        href: https://github.com/ayushrajdahal
      - icon: linkedin
        href: https://www.linkedin.com/in/ayushrajdahal
      # - icon: globe
      #   href: https://ayushraj.vercel.app/
format:
  html:
    theme: 
      light: litera
      # dark: [litera, theme-dark.scss]
    css: styles.css



