project:
  type: website
  output-dir: docs
website:
  title: "Ayush Raj Dahal"
  navbar:
    right:
      - blog.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/ayushrajdahal
      - icon: globe
        href: https://ayushraj.vercel.app/
format:
  html:
    theme: lux
    css: styles.css



